export type ICONS_CURSOR_TYPE = 
          'pointer' 
        | 'default'
        | 'inherit'

export type CUSTOM_ICONS_TYPE = 
        'sili'

export type NZ_ICONS_TYPE = 
          'bar-chart'
        | 'appstore'
        | 'car'
        | 'shop'
        | 'wallet'
        | 'team'
        | 'shopping'
        | 'home'
        | 'read'
        | 'shopping-cart'
        | 'apartment'
        | 'menu-fold'
        | 'menu-unfold'
        | 'arrow-left'
        | 'plus-circle'
        | 'delete'
        | 'edit'
        | 'dollar'
        | 'swap'
        | 'select'
        | 'logout'
        | 'clear'
        | 'check-circle'
        | 'down'
        | 'exclamation-circle'
        | 'sync'
        | 'close-circle'
        | 'loading'
        | 'double-left'
        | 'double-right'
        | 'global'
        | 'message'
        | 'phone'
        | 'star'
